### PR TITLE
Feature js communications protocol

### PR DESCRIPTION
**Pull request by zzeneric**
Implemented framework for communications protocol

### CODE REVIEW

**Comment by joshmackwilliams** [comment]
@zzeneric This pull request is on the `main` branch instead of `dev`. Can you make a new one to `dev` instead and close this one?

I have been looking through your changes and it looks great so far.

**Comment by zzeneric** [comment]
> @zzeneric This pull request is on the `main` branch instead of `dev`. Can you make a new one to `dev` instead and close this one?
> 
> I have been looking through your changes and it looks great so far.

I was able to switch the branch on this pull review, should be good to go.

**Comment by wheitman** [comment]
@zzeneric Just to be clear, this PR essentially adds [ros2-web-bridge ](https://github.com/RobotWebTools/ros2-web-bridge) to Navigator? Will your code be included in a separate PR?

**Comment by joshmackwilliams** [comment]
That's a lot of commits... are you still actively developing on this? If so, let's close the request and reopen it once it's done. Usually all the development should take place in a branch, and you can open a pull request once it's finished, so that it doesn't accidentally get merged when it isn't complete.

**Comment by wheitman** [comment]
Agreed. @zzeneric why don't we hold off on this PR for a week, then you can make a fresh one in time for our 1.2 release, which @joshmackwilliams will put together next week? Closing.

**Pull request closed without merging**
