### PR TITLE
Feature js communications protocol

### PR DESCRIPTION
**Pull request by zzeneric**
New communications protocol between Navigator and new frontend visualizer.

### CODE REVIEW

**Comment by joshmackwilliams** [comment]
@zzeneric looks like there's a merge conflict with main.launch.py. Can you look into that?

**Comment by joshmackwilliams** [comment]
Also, you've accidentally opened the request to `main` instead of `dev`

**Comment by joshmackwilliams** [comment]
Ok, so I haven't tested it yet, but looking through the code: 

1. Looks like you accidentally committed to some files that didn't really need to be committed (at least not in this PR), including `.vscde/settings`, `rosdep.sh`, `src/external/nova_dash/package-lock.json`, `src/interface/epas_translator/launch/container.launch.py`, and `src/common/had_map_utils/CMakeLists.txt`. I'm also unsure about the change in `src/perception/filters/voxel_grid_nodes/package.xml`. If any of these were intentional, that's fine, but it looks to me like they weren't meant to be in this PR. 

2. I have to test this to be sure (and I will test it later today), but I think OBJECT libraries are causing problems with the --symlink-install colcon argument (which we use fairly regularly). There's at least one in this PR, in `src/bridging/bridge_manager/CMakeLists.txt` on line 24. So to avoid issues, it should probably be changed to static. 

3. There are two copies of the file HTTPRequest.hpp. I'd like to avoid including duplicate files, so it would be best if we could use the same file in both packages. To accomplish this, you could create an `http` package that's included by both the other packages. Or you could combine `bridge_manager` and `bridge` into just the `bridge` package, since they're so closely related. 

Other than that, this PR looks like it's ready to go. I'll test it on the quad later today and let you know if I find anything else.

**Comment by joshmackwilliams** [comment]
@zzeneric Building on the quad gives me the following error: 
```
--- stderr: bridge_manager                                                                                                                     
/home/joshua/navigator/src/bridging/bridge_manager/test/test_bridge_manager.cpp:17:10: fatal error: voltron_msgs/srv/safety_event.hpp: No such file or directory
   17 | #include "voltron_msgs/srv/safety_event.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
I think it's because this branch is behind `dev`, so the new files aren't in here. This could be masked by old build files still persisting in the `install` folder. So, let's merge `dev` into this branch to try to resolve this.

**Comment by wheitman** [comment]
This looks pretty stale. I'm going to close it, and we can open a fresh one later.

**Pull request closed without merging**
