### PR TITLE
Feature obstacle republisher

### PR DESCRIPTION
**Pull request by rae0924**
Created 3 packages:
- obstacle_repub: contains a single src file that creates a node to republish obstacle data from SVL and Zed. Package has been directly tested on the SVL, however hasn't been directly tested for Zed wrapper outputs. Instead I wrote a gtest to mimic incoming Zed obstacles, and it seems to work fine processing that. In the future I need to test this package directly for Zed.
- obstacle_classes: this package simply just contains the enum declaration for the obstacle classes. I created this as a standalone library so others could use it to deal with obstacle labels.
- obstacle_drawer: can be used to draw 3-D obstacle bounding boxes in RViz with markers by subscribing to outputs from obstacle_repub. Seems to work flawlessly. Might add gtests in the future, but this is just a visualization package so it's not of priority.

Other things to note:
- added 2 nodes into main.launch.py file, each for obstacle_repub and obstacle_drawer
- we will need to add the 3D ground truth sensor to the SVL sensor config with a matching topic as one defined in obstacle_repub, with base_link as the frame.
- we will also need to add a component to the default rviz config file, that being marker array, subscribed to the topic /obstacles/marker_array to see the 3-D bounding boxes in rviz from obstacle_drawer.
- added git submodules under src/msg/ for required lsgvl_msgs and zed_interfaces packages. Also defined our own abstract formats under voltron_msgs.
- I will patch stuff in the future when I get to test the object detection outputs directly from the Zed wrapper using the camera.

### CODE REVIEW

**Comment by joshmackwilliams** [comment]
Just fixed a couple merge conflicts. I'm currently reviewing this for merging into dev, just in time for 1.2

**Comment by joshmackwilliams** [comment]
@rae0924 I'm getting the following error when building this branch on the quad: 
```
CMake Error at CMakeLists.txt:26 (find_package):
  By not providing "Findzed_interfaces.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "zed_interfaces", but CMake did not find one.

  Could not find a package configuration file provided by "zed_interfaces"
  with any of the following names:

    zed_interfacesConfig.cmake
    zed_interfaces-config.cmake

  Add the installation prefix of "zed_interfaces" to CMAKE_PREFIX_PATH or set
  "zed_interfaces_DIR" to a directory containing one of the above files.  If
  "zed_interfaces" provides a separate development package or SDK, be sure it
  has been installed.
```
Are you getting this error as well?

**Comment by rae0924** [comment]
@joshmackwilliams ok since I added git submodules, you need recursively clone these modules by using --recursive. [Link to stackoverflow](https://stackoverflow.com/questions/3796927/how-to-git-clone-including-submodules#:~:text=Original%20answer%202010%20As%20joschi%20mentions%20in%20the,registered%20submodules%2C%20and%20update%20any%20nested%20submodules%20within.). I think if you already cloned it git submodule update --init also works.

**Comment by joshmackwilliams** [comment]
Ah, I see. @wheitman what is your opinion on this? I know we decided to simply include Autoware's source instead of using submodules - should we apply the same logic here, or just leave this package as a submodule?

**Comment by wheitman** [comment]
@joshmackwilliams @rae0924 would really prefer copying relevant message files and other source code from the ZED libraries instead of using submodules. This can be as simple as cloning the ZED ROS2 wrapper packages into our source directory. Submodules add a certain level of complexity and variability that is not necessary at this time.

**Comment by rae0924** [comment]
okay then, we could just have those message repositories directly cloned into ours under src/msg/, I'll try to leave that to you guys. Let me know if you have any other concerns or want me to do something.

**Comment by wheitman** [comment]
> okay then, we could just have those message repositories directly cloned into ours under src/msg/, I'll try to leave that to you guys. Let me know if you have any other concerns or want me to do something.

Actually, if you could add those messages to `src/msg/voltron_msgs/msg/` in a new commit, update appropriate references from zed_interfaces to voltron_msgs, verify a fresh build (delete build cache first), and recommit, that would help us out!

Shouldn't be too big of a fix, but Josh and I are just really tied up at the moment. I'm excited to see this working on the car :)

**Comment by rae0924** [comment]
@joshmackwilliams I've added the message packages directly into the repo, however, i got the same issue as you did when compiling. For some reason cmake doesn't recognize "zed_interfaces" as a package or get its config files even though it was built before compiling obstacle_repub package. For some reason after the initial fail, after I've done ". install/setup.bash" command, I've lost the error for compilation and it build obstacle_repub successfully. IDK why this might be the case for just the "zed_interfaces" package, but not the other packages like "lgsvl_msgs" that "obstacle_repub" depends on.

**Comment by joshmackwilliams** [comment]
Also, whenever you do this, let's also rename the folder from `zed-ros2-interfaces` to `zed_interfaces`, so that the folder name matches the package name, for consistency with the rest of the project

**Comment by rae0924** [comment]
Thanks for the heads up, I have fixed the issues and have committed them.

**Review by joshmackwilliams — CHANGES_REQUESTED** [review]
@rae0924 I've reviewed everything and almost all of it looks great. The only change I'd like to request is that the tests for obstacle_repub be reworked a little bit. Right now, the test doesn't actually test the node itself. Instead, it just shuffles data back and forth between message formats, which isn't all that meaningful. I'd prefer it if the test actually spun up an instance of the node and verified it's behavior. If you need help doing that, let me know.

**Comment by rae0924** [comment]
@joshmackwilliams can you warn me beforehand if you are gonna commit some of the stuff in the packages? It caused some annoying merge conflicts while I was still editing the source code and writing the tests, probably because I added tests to obstacle_drawer. I reverted a lot of the cmakelists.txt stuff that you committed earlier because it was breaking my tests. You can add whatever changes you'd like to the cmakelists now, sorry for reversing some of your work.

**Comment by joshmackwilliams** [comment]
@rae0924 that's fine - using the automatic CMakeLists is not mandatory. However, as a side effect, you now have linting errors again, which is why I changed CMakeLists to begin with. Feel free to fix that however you want, but make sure that `colcon test --packages-select <your packages>` doesn't throw any errors, since we can't merge this with failing tests.

**Comment by rae0924** [comment]
the tests seem to be successful on the quad. I added remapping to the main.launch.py for topic names, can you check if that is how you are supposed to do it? Also is the main.launch.py supposed to be broken? Because whenever I launch it keeps throwing errors even if my packages are not launched. Otherwise, I think we are good to go for this PR, we just need to do testing with the car itself.

**Comment by joshmackwilliams** [comment]
@rae0924 To reproduce the test failures on the quad, you need to check out and build the most recent version of this branch, then run `colcon test --packages-select obstacle_classes obstacle_drawer obstacle_repub` in the project root. You will see that there are 15 failures, caused by code linting. These failures are validated by the automated tests, which are also failing (see the "checks" tab at the top of the page). We cannot merge the PR until this is resolved. 

I will look into the issue with main.launch.py, but for now I'm not too worried about it. It seems to behave the same way on `dev` as well, so that's not a problem for this PR. I also don't think that on-car testing will be necessary before merging, since these packages can be thoroughly tested in software. 

If you need help fixing the linting issues, send me a message on Teams.

**Comment by rae0924** [comment]
The 3 packages seem to not have any issues on my end when it comes to tests. It should be good to go.

**Review by joshmackwilliams — APPROVED** [review]

**Pull request merged**
